#define TYPE 1
#define NAME 2
#define TABLE_PREFIX 3
#define PORT 4
#define COLON 5
#define IDENTIFIER 6
#define INTEGER 7
#define IF 8
#define ELSE 9
#define THEN 10
#define ID 11
#define NUMBER 12
#define RELOP 13
#define LT 14
#define LE 15
#define EQ 16
#define NE 17
#define GT 18
#define GE 19
#define CLASS 20